global:
  scrape_interval: 30s   # 기본 수집 주기
  evaluation_interval: 30s  # 규칙 평가 주기

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093  # Alertmanager 설정 (필요하면 활성화)

rule_files:  # 규칙 파일 (필요하면 추가)

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]  # Prometheus 자체를 모니터링

  - job_name: "spring-actuator"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 30s
    static_configs:
      - targets: [ "sunsuwedding-app:8080" ]  # 컨테이너 네트워크 사용